# Generated by Django 3.2.12 on 2023-04-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_user', models.CharField(max_length=60)),
                ('receive_user', models.IntegerField(max_length=60)),
                ('state', models.BooleanField(default=False)),
                ('amount', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
