# Generated by Django 3.2.12 on 2023-04-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_receive_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='monetary_unit',
            field=models.CharField(default=4, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
