# Generated by Django 4.2 on 2023-04-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20230429_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='allow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
