# Generated by Django 3.2.12 on 2023-04-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=60)),
                ('balance', models.IntegerField(max_length=60)),
                ('monetary_unit', models.CharField(max_length=60)),
            ],
        ),
    ]
